#!/usr/bin/env python3
"""Build per-language JS dicts from translations.json (run on a normal filesystem).
   python3 build_i18n.py  -> regenerates en/fr/es/de/wo.js next to translations.json"""
import json
from pathlib import Path
HERE = Path(__file__).resolve().parent
SRC = HERE / 'translations.json'
def jq(s): return s.replace('\\', '\\\\').replace("'", "\\'").replace('\n', '\\n').replace('\r', '\\r')
def emit(node, ind):
    pad2 = ' ' * (ind + 2); lines = ['{']
    for k, v in node.items():
        kr = k if k.isidentifier() else "'" + jq(k) + "'"
        if isinstance(v, dict): lines.append(pad2 + kr + ': ' + emit(v, ind + 2) + ',')
        else: lines.append(pad2 + kr + ": '" + jq(v) + "',")
    lines.append(' ' * ind + '}'); return '\n'.join(lines)
def build(data, code):
    root = {}
    for ns, d in data['namespaces'].items():
        out = {}
        for key, lang in d.items():
            if code in lang:
                cur = out; parts = key.split('.')
                for p in parts[:-1]: cur = cur.setdefault(p, {})
                cur[parts[-1]] = lang[code]
        if out: root[ns] = out
    labels = {}
    if code != 'en':
        for eng, lang in data.get('labels', {}).items():
            if code in lang: labels[eng] = lang[code]
    parts = ['  ' + ns + ': ' + emit(out, 2) + ',' for ns, out in root.items()]
    if labels:
        ll = ["    '" + jq(e) + "': '" + jq(v) + "'," for e, v in labels.items()]
        parts.append('  labels: {\n' + '\n'.join(ll) + '\n  },')
    else:
        parts.append('  labels: {},')
    return ('// ' + code + '.js — auto-generated by build_i18n.py. Edit translations.json instead.\n'
            + 'window.I18N_' + code + ' = {\n' + '\n'.join(parts) + '\n};\n')
data = json.loads(SRC.read_text(encoding='utf-8'))
for code in data['_meta']['languages']:
    (HERE / (code + '.js')).write_text(build(data, code), encoding='utf-8')
    print('wrote', code + '.js')
